from typing import Protocol
from uuid import UUID

from arasaac_platform.domain.materials import AuditEvent, Material


class Repository(Protocol):
    def save(self, material: Material) -> Material: ...

    def get(self, material_id: UUID) -> Material: ...

    def list_materials(self) -> list[Material]: ...

    def append_event(self, event: AuditEvent) -> None: ...

    def events_for(self, material_id: UUID) -> list[AuditEvent]: ...

    def clear(self) -> None: ...
